
import { User, UserRole, Specialty, Case, CaseStatus, Translation } from './types';

export const APP_NAME = "2nd Opinion";
export const CASE_FEE = 40.00;
export const DOCTOR_PAYOUT = 28.00;
export const PLATFORM_FEE = 12.00;

// Mock Data Seeding
export const MOCK_USERS: User[] = [
  {
    id: 'p1',
    name: 'Ahmed Al-Sayed',
    email: 'ahmed@example.com',
    password: 'password123',
    role: UserRole.PATIENT,
    walletBalance: 100.00,
    avatarUrl: 'https://picsum.photos/id/1005/200/200',
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'd1',
    name: 'Dr. Sarah Smith',
    email: 'sarah@clinic.com',
    password: 'password123',
    role: UserRole.DOCTOR,
    walletBalance: 560.00,
    specialty: Specialty.CARDIOLOGY,
    hospital: 'Mayo Clinic',
    country: 'USA',
    rating: 4.8,
    casesClosed: 42,
    avatarUrl: 'https://picsum.photos/id/1011/200/200',
    linkedin: 'https://www.linkedin.com/',
    bio: 'Experienced Cardiologist with over 15 years in interventional cardiology. Dedicated to patient education and preventive care.',
    bonusPoints: 120,
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'd2',
    name: 'Dr. Karim Nader',
    email: 'karim@hospital.ae',
    password: 'password123',
    role: UserRole.DOCTOR,
    walletBalance: 1200.00,
    specialty: Specialty.DERMATOLOGY,
    hospital: 'Cleveland Clinic Abu Dhabi',
    country: 'UAE',
    rating: 4.9,
    casesClosed: 89,
    avatarUrl: 'https://picsum.photos/id/1025/200/200',
    linkedin: 'https://www.linkedin.com/',
    bio: 'Specializing in complex dermatological conditions and immunotherapy. Board certified in both UAE and UK.',
    bonusPoints: 350,
    isApproved: true,
    createdAt: new Date().toISOString()
  },
  {
    id: 'a1',
    name: 'Admin User',
    email: 'admin@2ndopinion.com',
    password: 'admin',
    role: UserRole.ADMIN,
    walletBalance: 5000.00, // Platform revenue wallet
    avatarUrl: 'https://picsum.photos/id/1025/200/200',
    isApproved: true,
    createdAt: new Date().toISOString()
  }
];

// Arabic Data Overrides for Doctors
export const DOCTOR_DETAILS_AR: Record<string, { name: string, specialty: string, hospital: string, country: string }> = {
  'd1': {
    name: 'د. سارة سميث',
    specialty: 'أمراض القلب',
    hospital: 'مايو كلينك',
    country: 'الولايات المتحدة'
  },
  'd2': {
    name: 'د. كريم نادر',
    specialty: 'الجلدية',
    hospital: 'كليفلاند كلينك أبوظبي',
    country: 'الإمارات'
  }
};

export const MOCK_CASES: Case[] = [
  {
    id: 'c101',
    patientId: 'p1',
    patientName: 'Ahmed Al-Sayed',
    specialty: Specialty.DERMATOLOGY,
    status: CaseStatus.CLOSED,
    symptoms: 'Recurring rash on left arm, itchy during night.',
    files: [],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    assignedDoctorId: 'd2',
    opinion: {
      doctorId: 'd2',
      doctorName: 'Dr. Karim Nader',
      decision: 'Agree',
      notes: 'Standard eczema. Prescribed hydrocortisone.',
      createdAt: new Date(Date.now() - 86400000 * 4).toISOString()
    },
    patientRating: 5,
    patientFeedback: "Dr. Karim was thorough and reassuring. Highly recommended for dermatology issues.",
    isRare: false
  }
];

export const TRANSLATIONS: Translation = {
  // General App
  "app.title": { en: "2nd Opinion", ar: "الرأي الثاني" },
  "nav.login": { en: "Login", ar: "دخول" },
  "nav.logout": { en: "Logout", ar: "خروج" },
  "nav.howItWorks": { en: "How it Works", ar: "كيف يعمل" },
  "nav.specialists": { en: "Specialists", ar: "الأطباء" },
  "nav.reviews": { en: "Reviews", ar: "التقييمات" },
  "nav.getStarted": { en: "Get Started", ar: "ابدأ الآن" },
  
  // Footer
  "footer.desc": { en: "Connecting patients with world-class specialists for reliable second medical opinions, powered by AI and secure technology.", ar: "ربط المرضى بأطباء عالميين للحصول على رأي طبي ثانٍ موثوق، بدعم من الذكاء الاصطناعي وتقنيات آمنة." },
  "footer.platform": { en: "Platform", ar: "المنصة" },
  "footer.legal": { en: "Legal & Support", ar: "القانونية والدعم" },
  "footer.contact": { en: "Contact Us", ar: "اتصل بنا" },
  "footer.rights": { en: "All rights reserved.", ar: "جميع الحقوق محفوظة." },
  "footer.madeWith": { en: "Made with", ar: "صنع بـ" },
  "footer.forHealth": { en: "for better healthcare.", ar: "من أجل رعاية صحية أفضل." },
  "link.findDoctor": { en: "Find a Doctor", ar: "ابحث عن طبيب" },
  "link.privacy": { en: "Privacy Policy", ar: "سياسة الخصوصية" },
  "link.terms": { en: "Terms of Service", ar: "شروط الخدمة" },
  "link.hipaa": { en: "HIPAA Compliance", ar: "الامتثال لقانون HIPAA" },
  "link.help": { en: "Help Center", ar: "مركز المساعدة" },
  "link.guide": { en: "User Guide", ar: "دليل المستخدم" },

  // Auth
  "auth.loginTitle": { en: "Welcome Back", ar: "مرحباً بعودتك" },
  "auth.loginDesc": { en: "Enter your credentials to access your account.", ar: "أدخل بيانات اعتمادك للوصول إلى حسابك." },
  "auth.email": { en: "Email Address", ar: "البريد الإلكتروني" },
  "auth.password": { en: "Password", ar: "كلمة المرور" },
  "auth.submitLogin": { en: "Sign In", ar: "تسجيل الدخول" },
  "auth.noAccount": { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
  "auth.registerLink": { en: "Register Now", ar: "سجل الآن" },
  "auth.registerTitle": { en: "Create Account", ar: "إنشاء حساب" },
  "auth.registerPatient": { en: "I am a Patient", ar: "أنا مريض" },
  "auth.registerDoctor": { en: "I am a Doctor", ar: "أنا طبيب" },
  "auth.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "auth.specialty": { en: "Specialty", ar: "التخصص" },
  "auth.hospital": { en: "Current Hospital", ar: "المستشفى الحالي" },
  "auth.country": { en: "Country", ar: "الدولة" },
  "auth.linkedin": { en: "LinkedIn Profile URL", ar: "رابط ملف LinkedIn" },
  "auth.bio": { en: "Short Bio", ar: "نبذة مختصرة" },
  "auth.photo": { en: "Profile Photo", ar: "صورة الملف الشخصي" },
  "auth.submitRegister": { en: "Create Account", ar: "إنشاء حساب" },
  "auth.alreadyAccount": { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  "auth.loginLink": { en: "Login here", ar: "سجل الدخول هنا" },

  // Settings
  "settings.title": { en: "Profile Settings", ar: "إعدادات الملف الشخصي" },
  "settings.updateBtn": { en: "Update Profile", ar: "تحديث الملف الشخصي" },
  "settings.success": { en: "Profile updated successfully.", ar: "تم تحديث الملف الشخصي بنجاح." },
  "settings.changePhoto": { en: "Change Photo", ar: "تغيير الصورة" },

  // Doctor Dashboard - New
  "doctor.markRare": { en: "Mark as Rare / Educational Case", ar: "وضع علامة كحالة نادرة / تعليمية" },
  "doctor.rareCases": { en: "Rare Cases Library", ar: "مكتبة الحالات النادرة" },
  "doctor.community": { en: "Community", ar: "المجتمع" },
  "doctor.anonymized": { en: "Anonymized Patient", ar: "مريض مجهول الهوية" },
  
  // Landing Page
  "landing.trusted": { en: "Trusted by 10,000+ Patients", ar: "موثوق من قبل أكثر من 10,000 مريض" },
  "landing.heroTitle1": { en: "Expert Medical", ar: "استشارات طبية" },
  "landing.heroTitle2": { en: "Second Opinions", ar: "رأي ثانٍ خبير" },
  "landing.heroDesc": { en: "Connect with world-class specialists to validate your diagnosis and treatment plan. Secure, fast, and powered by advanced AI assistance.", ar: "تواصل مع أطباء عالميين للتحقق من تشخيصك وخطة علاجك. آمن، سريع، ومدعوم بالذكاء الاصطناعي المتقدم." },
  "landing.dashboardBtn": { en: "Go to Dashboard", ar: "الذهاب للوحة التحكم" },
  "landing.demoPatient": { en: "Demo Patient", ar: "تجربة كمريض" },
  "landing.demoDoctor": { en: "Demo Doctor", ar: "تجربة كطبيب" },
  "landing.hipaa": { en: "HIPAA Compliant", ar: "متوافق مع HIPAA" },
  "landing.topDoctors": { en: "Top 1% Doctors", ar: "أفضل 1% من الأطباء" },
  "landing.imgBadgeDoctors": { en: "500+ Doctors", ar: "500+ طبيب" },
  "landing.imgBadgeReady": { en: "Ready to review your case today.", ar: "جاهزون لمراجعة حالتك اليوم." },
  
  "landing.stat.response": { en: "Avg. Response Time", ar: "متوسط وقت الرد" },
  "landing.stat.specialties": { en: "Specialties Covered", ar: "تخصص طبي" },
  "landing.stat.cases": { en: "Cases Resolved", ar: "حالة تم حلها" },
  "landing.stat.satisfaction": { en: "Patient Satisfaction", ar: "رضا المرضى" },

  "landing.why.title": { en: "Why Choose 2nd Opinion?", ar: "لماذا تختار الرأي الثاني؟" },
  "landing.why.desc": { en: "We combine top-tier medical expertise with advanced technology to give you the clarity you deserve.", ar: "نجمع بين الخبرة الطبية رفيعة المستوى والتكنولوجيا المتقدمة لمنحك الوضوح الذي تستحقه." },
  
  "landing.feature1.title": { en: "Verified Specialists", ar: "أطباء معتمدون" },
  "landing.feature1.desc": { en: "Access a global network of board-certified doctors. Every specialist is vetted, licensed, and reviewed by patients like you.", ar: "الوصول إلى شبكة عالمية من الأطباء المعتمدين. يتم فحص كل متخصص وترخيصه وتقييمه من قبل مرضى مثلك." },
  
  "landing.feature2.title": { en: "Fast Turnaround", ar: "سرعة في الإنجاز" },
  "landing.feature2.desc": { en: "Anxiety shouldn't wait. Receive a comprehensive second opinion report within 24-48 hours of submission.", ar: "القلق لا يجب أن ينتظر. احصل على تقرير رأي ثانٍ شامل في غضون 24-48 ساعة من التقديم." },
  
  "landing.feature3.title": { en: "AI-Enhanced Analysis", ar: "تحليل معزز بالذكاء الاصطناعي" },
  "landing.feature3.desc": { en: "Our Gemini AI pre-analyzes your history and labs to highlight key data points, ensuring your doctor misses nothing.", ar: "يقوم نموذج Gemini AI الخاص بنا بتحليل تاريخك وتحاليلك مسبقًا لتسليط الضوء على البيانات الرئيسية، مما يضمن عدم تفويت طبيبك لأي شيء." },

  "landing.leaderboard.title": { en: "Top Rated Specialists", ar: "الأطباء الأعلى تقييماً" },
  "landing.leaderboard.subtitle": { en: "Doctors recognized for their accuracy and patient care this month.", ar: "أطباء تم تكريمهم لدقتهم ورعايتهم للمرضى هذا الشهر." },
  "landing.leaderboard.viewAll": { en: "View All Doctors", ar: "عرض جميع الأطباء" },
  "landing.leaderboard.cases": { en: "cases closed", ar: "حالة مغلقة" },
  "landing.leaderboard.bonus": { en: "bonus pts", ar: "نقاط مكافأة" },
  "landing.adminDemo": { en: "Access Admin Portal (Demo)", ar: "دخول بوابة المسؤول (تجريبي)" },

  "role.patient": { en: "Patient", ar: "مريض" },
  "role.doctor": { en: "Doctor", ar: "طبيب" },
  "role.admin": { en: "Admin", ar: "مسؤول" },
  "wallet.balance": { en: "Wallet Balance", ar: "رصيد المحفظة" },
  "btn.newCase": { en: "New Case", ar: "حالة جديدة" },
  "status.open": { en: "Open", ar: "مفتوحة" },
  "status.closed": { en: "Closed", ar: "مغلقة" },
  "status.pendingInfo": { en: "Pending Info", ar: "بانتظار معلومات" },
  "label.symptoms": { en: "Describe Symptoms", ar: "وصف الأعراض" },
  "label.specialty": { en: "Specialty", ar: "التخصص" },
  "ai.analyze": { en: "AI Analyze", ar: "تحليل الذكاء الاصطناعي" },
  "ai.refine": { en: "AI Refine", ar: "تحسين النص" },

  // Admin Dashboard
  "admin.title": { en: "Admin Dashboard", ar: "لوحة تحكم المسؤول" },
  "admin.tab.overview": { en: "Overview", ar: "نظرة عامة" },
  "admin.tab.users": { en: "User Management", ar: "إدارة المستخدمين" },
  "admin.reset": { en: "Reset Demo Data", ar: "إعادة تعيين البيانات التجريبية" },
  "admin.kpi.totalCases": { en: "Total Cases", ar: "إجمالي الحالات" },
  "admin.kpi.activeDoctors": { en: "Active Doctors", ar: "الأطباء النشطون" },
  "admin.kpi.volume": { en: "Total Volume", ar: "إجمالي التداول" },
  "admin.kpi.profit": { en: "Net Profit (30%)", ar: "صافي الربح (30%)" },
  "admin.chart.specialty": { en: "Cases by Specialty", ar: "الحالات حسب التخصص" },
  "admin.chart.topDocs": { en: "Top Doctors (Cases Closed)", ar: "أفضل الأطباء (حالات مغلقة)" },
  "admin.table.title": { en: "Recent Case Submissions", ar: "أحدث الحالات المقدمة" },
  "admin.filter.all": { en: "All Statuses", ar: "جميع الحالات" },
  "admin.searchPlaceholder": { en: "Search patient or ID...", ar: "ابحث عن مريض أو رقم تعريفي..." },
  "admin.th.caseId": { en: "Case ID", ar: "رقم الحالة" },
  "admin.th.patient": { en: "Patient", ar: "المريض" },
  "admin.th.specialty": { en: "Specialty", ar: "التخصص" },
  "admin.th.status": { en: "Status", ar: "الحالة" },
  "admin.th.doctor": { en: "Doctor", ar: "الطبيب" },
  "admin.th.date": { en: "Date", ar: "التاريخ" },
  "admin.unassigned": { en: "Unassigned", ar: "غير معين" },
  "admin.noCases": { en: "No cases found matching filters.", ar: "لا توجد حالات تطابق الفلاتر." },
  
  // Admin User Management
  "admin.users.search": { en: "Search users...", ar: "بحث عن مستخدمين..." },
  "admin.users.approve": { en: "Approve", ar: "موافقة" },
  "admin.users.reject": { en: "Reject", ar: "رفض" },
  "admin.users.delete": { en: "Delete", ar: "حذف" },
  "admin.users.pending": { en: "Pending Approval", ar: "بانتظار الموافقة" },
  "admin.users.active": { en: "Active", ar: "نشط" },

  // HIPAA Page
  "hipaa.badge": { en: "Security First Platform", ar: "منصة الأمان أولاً" },
  "hipaa.title": { en: "HIPAA Compliance & Data Security", ar: "الامتثال لـ HIPAA وأمن البيانات" },
  "hipaa.heroDesc": { en: "We adhere to the strictest standards of the Health Insurance Portability and Accountability Act (HIPAA) to ensure your sensitive medical information remains private, secure, and accessible only to authorized specialists.", ar: "نلتزم بأشد معايير قانون نقل التأمين الصحي والمساءلة (HIPAA) لضمان بقاء معلوماتك الطبية الحساسة خاصة وآمنة ومتاحة فقط للمتخصصين المصرح لهم." },
  "hipaa.encryption": { en: "Encryption", ar: "التشفير" },
  "hipaa.atRest": { en: "AES-256 (At Rest)", ar: "AES-256 (عند التخزين)" },
  "hipaa.transmission": { en: "Transmission", ar: "النقل" },
  "hipaa.inTransit": { en: "TLS 1.3 (In Transit)", ar: "TLS 1.3 (أثناء النقل)" },
  "hipaa.access": { en: "Access Control", ar: "التحكم في الوصول" },
  "hipaa.rbac": { en: "Role-Based (RBAC)", ar: "بناءً على الأدوار" },
  "hipaa.pillarsTitle": { en: "How We Protect Your Health Data", ar: "كيف نحمي بياناتك الصحية" },
  "hipaa.pillarsDesc": { en: "Our multi-layered security approach ensures compliance at every step.", ar: "نهجنا الأمني متعدد الطبقات يضمن الامتثال في كل خطوة." },
  "hipaa.e2eTitle": { en: "End-to-End Encryption", ar: "تشفير شامل" },
  "hipaa.e2eDesc": { en: "All patient records, medical images (DICOM), and chat logs are encrypted using military-grade AES-256 standards when stored in our databases.", ar: "يتم تشفير جميع سجلات المرضى والصور الطبية (DICOM) وسجلات المحادثات باستخدام معايير AES-256 العسكرية عند تخزينها." },
  "hipaa.auditTitle": { en: "Audit Trails & Monitoring", ar: "مسارات التدقيق والمراقبة" },
  "hipaa.auditDesc": { en: "Every interaction with Personal Health Information (PHI) is logged. We maintain detailed audit trails tracking who accessed data and when.", ar: "يتم تسجيل كل تفاعل مع المعلومات الصحية الشخصية (PHI). نحتفظ بمسارات تدقيق مفصلة تتبع من وصل للبيانات ومتى." },
  "hipaa.infraTitle": { en: "Secure Infrastructure", ar: "بنية تحتية آمنة" },
  "hipaa.infraDesc": { en: "Our servers are hosted in SOC 2 Type II certified data centers with strict physical security measures.", ar: "تتم استضافة خوادمنا في مراكز بيانات معتمدة SOC 2 Type II مع تدابير أمنية مادية صارمة." },
  "hipaa.baaTitle": { en: "Business Associate Agreement (BAA)", ar: "اتفاقية شراكة الأعمال (BAA)" },
  "hipaa.baaDesc": { en: "2nd Opinion signs a Business Associate Agreement (BAA) with all partner hospitals and healthcare providers.", ar: "توقع منصة الرأي الثاني اتفاقية شراكة أعمال (BAA) مع جميع المستشفيات ومقدمي الرعاية الصحية الشركاء." },
  "hipaa.rightsTitle": { en: "Patient Rights", ar: "حقوق المريض" },
  "hipaa.rightsDesc": { en: "Under HIPAA, you have specific rights regarding your health information:", ar: "بموجب HIPAA، لديك حقوق محددة فيما يتعلق بمعلوماتك الصحية:" },
  "hipaa.right1": { en: "Right to access and obtain a copy of your health records.", ar: "الحق في الوصول والحصول على نسخة من سجلاتك الصحية." },
  "hipaa.right2": { en: "Right to request corrections to your medical information.", ar: "الحق في طلب تصحيح معلوماتك الطبية." },
  "hipaa.right3": { en: "Right to know how and where your information is shared.", ar: "الحق في معرفة كيف وأين تتم مشاركة معلوماتك." },
  "hipaa.right4": { en: "Right to data portability.", ar: "الحق في نقل البيانات." },
  "hipaa.back": { en: "Back to Home", ar: "العودة للرئيسية" },

  // How It Works Page
  "how.badge": { en: "From doubt to clarity in 48 hours", ar: "من الشك إلى اليقين في 48 ساعة" },
  "how.title": { en: "Your path to a Confident Diagnosis", ar: "طريقك إلى تشخيص واثق" },
  "how.desc": { en: "We've simplified the complex process of getting a second medical opinion into four easy, secure steps.", ar: "لقد بسطنا العملية المعقدة للحصول على رأي طبي ثانٍ في أربع خطوات سهلة وآمنة." },
  "how.step1.title": { en: "Create Account", ar: "إنشاء حساب" },
  "how.step1.desc": { en: "Sign up as a patient. Securely deposit funds into your wallet.", ar: "سجل كمريض. أودع الأموال بأمان في محفظتك." },
  "how.step2.title": { en: "Submit Case Data", ar: "أرسل بيانات الحالة" },
  "how.step2.desc": { en: "Describe symptoms and upload labs. Our AI organizes this for the doctor.", ar: "صف الأعراض وحمل التحاليل. ينظم ذكاؤنا الاصطناعي هذا للطبيب." },
  "how.step3.title": { en: "Specialist Review", ar: "مراجعة المتخصص" },
  "how.step3.desc": { en: "A top-rated specialist reviews your case and files to form an opinion.", ar: "يقوم متخصص ذو تقييم عالٍ بمراجعة حالتك وملفاتك لتكوين رأي." },
  "how.step4.title": { en: "Get Your Report", ar: "احصل على تقريرك" },
  "how.step4.desc": { en: "Receive a detailed second opinion to validate your treatment.", ar: "استلم رأياً ثانياً مفصلاً للتحقق من علاجك." },
  "how.aiTitle": { en: "Powered by AI, Verified by Humans", ar: "مدعوم بالذكاء الاصطناعي، ومحقق من البشر" },
  "how.aiDesc": { en: "We use advanced Gemini AI models to assist our doctors, not replace them.", ar: "نستخدم نماذج Gemini AI المتقدمة لمساعدة أطبائنا، وليس لاستبدالهم." },
  "how.feature1": { en: "Smart Symptom Refinement", ar: "تحسين الأعراض الذكي" },
  "how.feature2": { en: "Data Privacy & Security", ar: "خصوصية وأمن البيانات" },
  "how.faqTitle": { en: "Frequently Asked Questions", ar: "الأسئلة الشائعة" },
  "how.faq1.q": { en: "How much does it cost?", ar: "كم التكلفة؟" },
  "how.faq1.a": { en: "Every standard second opinion case is a flat fee of $40.00.", ar: "كل حالة رأي ثانٍ قياسية لها رسوم ثابتة قدرها 40.00 دولارًا." },
  "how.faq2.q": { en: "Who are the doctors?", ar: "من هم الأطباء؟" },
  "how.faq2.a": { en: "Our specialists are board-certified professionals from top hospitals worldwide.", ar: "أطباؤنا متخصصون معتمدون من أفضل المستشفيات حول العالم." },
  "how.cta": { en: "Start Your Consultation", ar: "ابدأ استشارتك" },

  // Reviews Page
  "reviews.badge": { en: "Rated 4.9/5 by 10,000+ Patients", ar: "مقيم 4.9/5 من قبل 10,000+ مريض" },
  "reviews.title": { en: "Stories of Better Health", ar: "قصص صحة أفضل" },
  "reviews.desc": { en: "Real experiences from patients who found clarity and confidence through 2nd Opinion.", ar: "تجارب حقيقية من مرضى وجدوا الوضوح والثقة من خلال الرأي الثاني." },
  "reviews.stat.rating": { en: "Average Rating", ar: "متوسط التقييم" },
  "reviews.stat.recommend": { en: "Would Recommend", ar: "يوصون به" },
  "reviews.stat.time": { en: "Avg. Response Time", ar: "متوسط وقت الاستجابة" },
  "reviews.story.badge": { en: "Success Story", ar: "قصة نجاح" },
  "reviews.story.title": { en: "From Uncertainty to a Cure", ar: "من عدم اليقين إلى العلاج" },
  "reviews.story.text": { en: "\"I spent two years visiting different specialists with no clear answer. Within 48 hours of submitting my case to 2nd Opinion, Dr. Sarah Smith identified a rare condition that had been overlooked.\"", ar: "\"قضيت عامين أزور متخصصين مختلفين دون إجابة واضحة. في غضون 48 ساعة من تقديم حالتي إلى الرأي الثاني، حددت الدكتورة سارة سميث حالة نادرة تم إغفالها.\"" },
  "reviews.story.author": { en: "Verified Patient • California, USA", ar: "مريض موثق • كاليفورنيا، الولايات المتحدة" },
  "reviews.ctaTitle": { en: "Ready to find your answers?", ar: "هل أنت مستعد للعثور على إجاباتك؟" },
  
  // Find Doctors Page
  "findDoc.title": { en: "Find a Specialist", ar: "ابحث عن أخصائي" },
  "findDoc.searchPlaceholder": { en: "Search name, specialty...", ar: "ابحث بالاسم، التخصص..." },
  "findDoc.book": { en: "Book Consultation", ar: "حجز استشارة" },
  "findDoc.noResults": { en: "No specialists found matching your search.", ar: "لم يتم العثور على أطباء يطابقون بحثك." },
  "findDoc.location": { en: "Location", ar: "الموقع" },
  "findDoc.allLocations": { en: "All Locations", ar: "جميع المواقع" },

  // Privacy Policy
  "privacy.title": { en: "Privacy Policy", ar: "سياسة الخصوصية" },
  "privacy.intro": { en: "At 2nd Opinion, we are committed to protecting your privacy and ensuring the security of your personal health information. This Privacy Policy outlines how we collect, use, and safeguard your data.", ar: "في الرأي الثاني، نحن ملتزمون بحماية خصوصيتك وضمان أمان معلوماتك الصحية الشخصية. توضح سياسة الخصوصية هذه كيفية جمع بياناتك واستخدامها وحمايتها." },
  "privacy.collectionTitle": { en: "Information We Collect", ar: "المعلومات التي نجمعها" },
  "privacy.collectionDesc": { en: "We collect personal information including name, email, medical history, and uploaded documents strictly for the purpose of providing second medical opinions.", ar: "نقوم بجمع المعلومات الشخصية بما في ذلك الاسم والبريد الإلكتروني والتاريخ الطبي والمستندات التي تم تحميلها بدقة لغرض تقديم آراء طبية ثانية." },
  "privacy.usageTitle": { en: "How We Use Your Information", ar: "كيف نستخدم معلوماتك" },
  "privacy.usageDesc": { en: "Your data is shared only with the medical specialists reviewing your case. Anonymized data may be used for platform analytics and improvement.", ar: "تتم مشاركة بياناتك فقط مع الأخصائيين الطبيين الذين يراجعون حالتك. قد يتم استخدام البيانات مجهولة المصدر لتحليلات المنصة وتحسينها." },
  "privacy.securityTitle": { en: "Data Security", ar: "أمن البيانات" },
  "privacy.securityDesc": { en: "We implement industry-standard encryption and security measures complying with HIPAA regulations to protect your data during transmission and storage.", ar: "نقوم بتطبيق معايير التشفير والأمان المتوافقة مع لوائح HIPAA لحماية بياناتك أثناء النقل والتخزين." },

  // Terms of Service
  "terms.title": { en: "Terms of Service", ar: "شروط الخدمة" },
  "terms.intro": { en: "By accessing or using the 2nd Opinion platform, you agree to be bound by these Terms of Service.", ar: "من خلال الوصول إلى منصة الرأي الثاني أو استخدامها، فإنك توافق على الالتزام بشروط الخدمة هذه." },
  "terms.servicesTitle": { en: "Our Services", ar: "خدماتنا" },
  "terms.servicesDesc": { en: "2nd Opinion provides a platform for patients to obtain second medical opinions from qualified specialists. We do not provide direct medical treatment or emergency services.", ar: "توفر الرأي الثاني منصة للمرضى للحصول على آراء طبية ثانية من متخصصين مؤهلين. نحن لا نقدم علاجًا طبيًا مباشرًا أو خدمات طوارئ." },
  "terms.disclaimerTitle": { en: "Medical Disclaimer", ar: "إخلاء المسؤولية الطبية" },
  "terms.disclaimerDesc": { en: "The content and services provided on this platform are for informational purposes only and are not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician for any medical condition.", ar: "المحتوى والخدمات المقدمة على هذه المنصة للأغراض الإعلامية فقط وليست بديلاً عن المشورة الطبية المهنية أو التشخيص أو العلاج. اطلب دائمًا نصيحة طبيبك لأي حالة طبية." },
  "terms.paymentTitle": { en: "Payments and Refunds", ar: "المدفوعات والمبالغ المستردة" },
  "terms.paymentDesc": { en: "Fees for consultations are charged at the time of submission. Refunds are processed only if a case is cancelled before specialist review begins.", ar: "يتم فرض رسوم الاستشارات في وقت التقديم. تتم معالجة المبالغ المستردة فقط إذا تم إلغاء الحالة قبل بدء مراجعة الأخصائي." },

  // User Guide
  "guide.badge": { en: "Training Manual v1.0", ar: "دليل التدريب v1.0" },
  "guide.title": { en: "User Documentation", ar: "وثائق المستخدم" },
  "guide.desc": { en: "Comprehensive guide for Patients, Doctors, and Administrators on how to use the 2nd Opinion platform effectively.", ar: "دليل شامل للمرضى والأطباء والمسؤولين حول كيفية استخدام منصة الرأي الثاني بفعالية." },
  "guide.toc": { en: "Table of Contents", ar: "جدول المحتويات" },
  "guide.nav.intro": { en: "1. Overview", ar: "1. نظرة عامة" },
  "guide.nav.auth": { en: "2. Registration & Login", ar: "2. التسجيل والدخول" },
  "guide.nav.patient": { en: "3. Patient Guide", ar: "3. دليل المريض" },
  "guide.nav.doctor": { en: "4. Doctor Guide", ar: "4. دليل الطبيب" },
  "guide.nav.admin": { en: "5. Admin Guide", ar: "5. دليل المسؤول" },
  "guide.support.title": { en: "Need Support?", ar: "تحتاج مساعدة؟" },
  "guide.support.text": { en: "Contact our IT helpdesk for technical issues.", ar: "تواصل مع مكتب المساعدة الفنية لأي مشاكل." },
  "guide.intro.title": { en: "1. Overview", ar: "1. نظرة عامة" },
  "guide.intro.text": { en: "2nd Opinion is a secure, HIPAA-compliant SaaS platform connecting patients seeking second medical opinions with top-tier global specialists. The platform leverages Gemini AI to assist in symptom analysis and provides a seamless workflow for document upload, review, and payment.", ar: "الرأي الثاني هي منصة آمنة ومتوافقة مع HIPAA تربط المرضى الذين يبحثون عن آراء طبية ثانية بمتخصصين عالميين. تستفيد المنصة من Gemini AI للمساعدة في تحليل الأعراض وتوفر سير عمل سلس لتحميل المستندات والمراجعة والدفع." },
  "guide.screen.landing": { en: "Screenshot: Landing Page", ar: "لقطة شاشة: الصفحة الرئيسية" },
  "guide.auth.title": { en: "2. Registration & Login", ar: "2. التسجيل والدخول" },
  "guide.auth.createTitle": { en: "Creating an Account", ar: "إنشاء حساب" },
  "guide.auth.createText": { en: "New users must register by clicking 'Get Started'. During registration, you must select your role:", ar: "يجب على المستخدمين الجدد التسجيل بالنقر على 'ابدأ الآن'. أثناء التسجيل، يجب عليك اختيار دورك:" },
  "guide.auth.rolePatient": { en: "Patients: Immediate access upon registration.", ar: "المرضى: وصول فوري عند التسجيل." },
  "guide.auth.roleDoctor": { en: "Doctors: Requires providing credentials (License, Hospital, LinkedIn). Account status will be 'Pending' until approved by an Admin.", ar: "الأطباء: يتطلب تقديم بيانات الاعتماد (الترخيص، المستشفى، LinkedIn). ستكون حالة الحساب 'قيد الانتظار' حتى الموافقة عليها من قبل المسؤول." },
  "guide.auth.noteTitle": { en: "Note for Doctors", ar: "ملاحظة للأطباء" },
  "guide.auth.noteText": { en: "If you cannot login immediately after registering, it means your account is still under review. Please allow up to 24 hours for verification.", ar: "إذا لم تتمكن من تسجيل الدخول فوراً بعد التسجيل، فهذا يعني أن حسابك لا يزال قيد المراجعة. يرجى الانتظار حتى 24 ساعة للتحقق." },
  "guide.patient.title": { en: "3. Patient Guide", ar: "3. دليل المريض" },
  "guide.patient.dashTitle": { en: "Dashboard Overview", ar: "نظرة عامة على لوحة التحكم" },
  "guide.patient.dashText": { en: "The Patient Dashboard is your central hub. Here you can see your wallet balance, start new consultations, and track the status of existing cases.", ar: "لوحة تحكم المريض هي مركزك الرئيسي. هنا يمكنك رؤية رصيد محفظتك، وبدء استشارات جديدة، وتتبع حالة الحالات الحالية." },
  "guide.patient.submitTitle": { en: "Submitting a Case", ar: "تقديم حالة" },
  "guide.patient.step1": { en: "Start: Click the 'New Case' button in the sidebar.", ar: "البدء: انقر على زر 'حالة جديدة' في الشريط الجانبي." },
  "guide.patient.step2": { en: "Select Specialty: Choose the medical category relevant to your condition.", ar: "اختر التخصص: اختر الفئة الطبية ذات الصلة بحالتك." },
  "guide.patient.step3": { en: "Describe Symptoms (AI Assisted): Type your symptoms in the text box.", ar: "وصف الأعراض (بمساعدة AI): اكتب أعراضك في مربع النص." },
  "guide.patient.proTip": { en: "Pro Tip: Click 'AI Refine' to have Gemini AI rewrite your description into clearer clinical terms for the doctor.", ar: "نصيحة محترف: انقر على 'تحسين AI' ليقوم Gemini AI بإعادة كتابة وصفك بمصطلحات طبية أوضح للطبيب." },
  "guide.patient.step4": { en: "Payment: The $40.00 fee is deducted automatically from your wallet. Ensure you have sufficient funds (use the Deposit button if needed).", ar: "الدفع: يتم خصم الرسوم البالغة 40.00 دولاراً تلقائياً من محفظتك. تأكد من وجود رصيد كافٍ (استخدم زر الإيداع إذا لزم الأمر)." },
  "guide.patient.findDocTitle": { en: "Finding a Specific Doctor", ar: "البحث عن طبيب معين" },
  "guide.patient.findDocText": { en: "Instead of the general pool, you can request a specific specialist. Go to the 'Find Doctors' tab, search by name or hospital, and view their full profile before booking.", ar: "بدلاً من المجموعة العامة، يمكنك طلب متخصص معين. انتقل إلى علامة تبويب 'البحث عن أطباء'، وابحث بالاسم أو المستشفى، واعرض ملفهم الشخصي الكامل قبل الحجز." },
  "guide.doctor.title": { en: "4. Doctor Guide", ar: "4. دليل الطبيب" },
  "guide.doctor.discoveryTitle": { en: "Case Discovery", ar: "اكتشاف الحالات" },
  "guide.doctor.discoveryText": { en: "Your dashboard shows 'Available Cases' filtered by your specialty.", ar: "تعرض لوحة التحكم الخاصة بك 'الحالات المتاحة' المصفاة حسب تخصصك." },
  "guide.doctor.directReq": { en: "Direct Requests: Cases assigned specifically to you are highlighted in purple with a star badge.", ar: "الطلبات المباشرة: الحالات المعينة لك خصيصاً مميزة باللون الأرجواني مع شارة نجمة." },
  "guide.doctor.reviewTitle": { en: "Reviewing a Case", ar: "مراجعة حالة" },
  "guide.doctor.reviewText": { en: "Click on any case to open the detailed view.", ar: "انقر على أي حالة لفتح العرض التفصيلي." },
  "guide.doctor.reviewList1": { en: "Patient History: Read the symptoms and download attached files.", ar: "تاريخ المريض: اقرأ الأعراض وقم بتنزيل الملفات المرفقة." },
  "guide.doctor.reviewList2": { en: "AI Insights: Review the automated analysis provided by Gemini AI to spot key indicators quickly.", ar: "رؤى AI: راجع التحليل الآلي المقدم من Gemini AI لاكتشاف المؤشرات الرئيسية بسرعة." },
  "guide.doctor.reviewList3": { en: "Action Console: Choose to Agree, Disagree, or Request More Tests.", ar: "وحدة التحكم بالإجراءات: اختر الموافقة، عدم الموافقة، أو طلب المزيد من الاختبارات." },
  "guide.doctor.profileTitle": { en: "Profile Settings", ar: "إعدادات الملف الشخصي" },
  "guide.doctor.profileText": { en: "Keep your profile updated to attract more patients. Click the Settings (Gear Icon) to update your Bio, Hospital, LinkedIn URL, and Profile Photo.", ar: "حافظ على تحديث ملفك الشخصي لجذب المزيد من المرضى. انقر على الإعدادات (أيقونة الترس) لتحديث نبذتك، المستشفى، رابط LinkedIn، وصورة الملف الشخصي." },
  "guide.admin.title": { en: "5. Admin Guide", ar: "5. دليل المسؤول" },
  "guide.admin.platformTitle": { en: "Platform Overview", ar: "نظرة عامة على المنصة" },
  "guide.admin.platformText": { en: "The Admin Dashboard provides real-time metrics on total revenue, active doctors, and case volume. Use the charts to identify trending specialties.", ar: "توفر لوحة تحكم المسؤول مقاييس في الوقت الفعلي حول إجمالي الإيرادات، الأطباء النشطين، وحجم الحالات. استخدم الرسوم البيانية لتحديد التخصصات الرائجة." },
  "guide.admin.usersTitle": { en: "Managing Users", ar: "إدارة المستخدمين" },
  "guide.admin.usersText": { en: "Navigate to the 'User Management' tab to approve new doctor registrations.", ar: "انتقل إلى علامة تبويب 'إدارة المستخدمين' للموافقة على تسجيلات الأطباء الجدد." },
  "guide.admin.usersList1": { en: "Approve: Grants the doctor access to the platform.", ar: "موافقة: تمنح الطبيب حق الوصول إلى المنصة." },
  "guide.admin.usersList2": { en: "Reject/Suspend: Revokes access immediately.", ar: "رفض/تعليق: يلغي الوصول فوراً." },
};
